<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JenisPenyakitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $lists = [
            array("kelompok_penyakit_id" => 1, "nama" => "Alergi Makanan", "icd10" => "L27.2"),
            array("kelompok_penyakit_id" => 1, "nama" => "Chikungunya", "icd10" => "A92.0"),
            array("kelompok_penyakit_id" => 1, "nama" => "Demam Berdarah Dengue", "icd10" => "A91"),
            array("kelompok_penyakit_id" => 1, "nama" => "Demam Dengue", "icd10" => "A90"),
            array("kelompok_penyakit_id" => 1, "nama" => "Filariasis", "icd10" => "B74"),
            array("kelompok_penyakit_id" => 1, "nama" => "Infeksi pada Umbilikus", "icd10" => "P38"),
            array("kelompok_penyakit_id" => 1, "nama" => "Kandidiasis Mulut", "icd10" => "B37.9"),
            array("kelompok_penyakit_id" => 1, "nama" => "Keracunan Makanan", "icd10" => "T62.2"),
            array("kelompok_penyakit_id" => 1, "nama" => "Lepra", "icd10" => "A30"),
            array("kelompok_penyakit_id" => 1, "nama" => "Leptospirosis", "icd10" => "A27.9"),
            array("kelompok_penyakit_id" => 1, "nama" => "Malaria", "icd10" => "B54"),
            array("kelompok_penyakit_id" => 1, "nama" => "Morbili (Campak)", "icd10" => "B05.9"),
            array("kelompok_penyakit_id" => 1, "nama" => "Reaksi Anafilaktik", "icd10" => "T78.2"),
            array("kelompok_penyakit_id" => 1, "nama" => "Syok", "icd10" => "R57.9 "),
            array("kelompok_penyakit_id" => 1, "nama" => "TB Selain Paru (Ekstra Paru)", "icd10" => "A18"),
            array("kelompok_penyakit_id" => 1, "nama" => "Tuberkulosis (TB) Paru", "icd10" => "A15"),
            array("kelompok_penyakit_id" => 1, "nama" => "Tuberkulosis dengan HIV", "icd10" => " B20.0"),
            array("kelompok_penyakit_id" => 1, "nama" => "Varisela", "icd10" => "B01.9"),
            array("kelompok_penyakit_id" => 2, "nama" => "Anemia Defisiensi Besi", "icd10" => "D50.9"),
            array("kelompok_penyakit_id" => 2, "nama" => "HIV/AIDS Tanpa Komplikasi", "icd10" => "Z21"),
            array("kelompok_penyakit_id" => 2, "nama" => "Leukimia", "icd10" => "D55"),
            array("kelompok_penyakit_id" => 2, "nama" => "Limfadenitis", "icd10" => "B70"),
            array("kelompok_penyakit_id" => 2, "nama" => "Limfoma Maligna", "icd10" => "C85.9"),
            array("kelompok_penyakit_id" => 2, "nama" => "Lupus Eritematosus Sistemik", "icd10" => "M32"),
            array("kelompok_penyakit_id" => 2, "nama" => "Thalasemia", "icd10" => "D56"),
            array("kelompok_penyakit_id" => 3, "nama" => "Ankilostomiosis", "icd10" => "B76.0"),
            array("kelompok_penyakit_id" => 3, "nama" => "Apendisitis Akut", "icd10" => "K.35.9"),
            array("kelompok_penyakit_id" => 3, "nama" => "Askariasis", "icd10" => "B77.9"),
            array("kelompok_penyakit_id" => 3, "nama" => "Atresia (Ani) dengan atau tanpa Fistula", "icd10" => "Q42"),
            array("kelompok_penyakit_id" => 3, "nama" => "Bibir dan Langit-langit Sumbing", "icd10" => "Q37.9"),
            array("kelompok_penyakit_id" => 3, "nama" => "Bibir Sumbing", "icd10" => "Q36.9"),
            array("kelompok_penyakit_id" => 3, "nama" => "Demam Tifoid", "icd10" => "A01.0"),
            array("kelompok_penyakit_id" => 3, "nama" => "Disentri Basiler dan Disentri Amuba", "icd10" => "A06.0"),
            array("kelompok_penyakit_id" => 3, "nama" => "Gastritis", "icd10" => "K29.7"),
            array("kelompok_penyakit_id" => 3, "nama" => "Gastroenteritis (Kolera dan Giardiasis)", "icd10" => "A09"),
            array("kelompok_penyakit_id" => 3, "nama" => "Gastroschisis", "icd10" => "Q79.3"),
            array("kelompok_penyakit_id" => 3, "nama" => "Hemoroid grade 1-2", "icd10" => "I84"),
            array("kelompok_penyakit_id" => 3, "nama" => "Hepatitis A", "icd10" => "B15"),
            array("kelompok_penyakit_id" => 3, "nama" => "Hepatitis B", "icd10" => "B16"),
            array("kelompok_penyakit_id" => 3, "nama" => "Hepatitis C", "icd10" => "B18.2"),
            array("kelompok_penyakit_id" => 3, "nama" => "Intoleransi Makanan", "icd10" => "K90.4"),
            array("kelompok_penyakit_id" => 3, "nama" => "Kolesistitis", "icd10" => "K81.9"),
            array("kelompok_penyakit_id" => 3, "nama" => "Langit-langit Sumbing", "icd10" => "Q35"),
            array("kelompok_penyakit_id" => 3, "nama" => "Malabsorbsi Makanan", "icd10" => "K90.9"),
            array("kelompok_penyakit_id" => 3, "nama" => "Omphalocele", "icd10" => "Q79.2"),
            array("kelompok_penyakit_id" => 3, "nama" => "Parotitis", "icd10" => "B26"),
            array("kelompok_penyakit_id" => 3, "nama" => "Perdarahan Gastrointestinal (K92.2)", "icd10" => "K92.2"),
            array("kelompok_penyakit_id" => 3, "nama" => "Perdarahan Gastrointestinal (K62.5)", "icd10" => "K62.5"),
            array("kelompok_penyakit_id" => 3, "nama" => "Peritoniti", "icd10" => "K65.9"),
            array("kelompok_penyakit_id" => 3, "nama" => "Refluks Gastroesofageal", "icd10" => "K21.9"),
            array("kelompok_penyakit_id" => 3, "nama" => "Skistosomiasis (B65.9)", "icd10" => "B65.9"),
            array("kelompok_penyakit_id" => 3, "nama" => "Skistosomiasis (B65.2)", "icd10" => "B65.2"),
            array("kelompok_penyakit_id" => 3, "nama" => "Strongiloidiasis", "icd10" => "B78.9"),
            array("kelompok_penyakit_id" => 3, "nama" => "Taeniasis", "icd10" => "B68.9"),
            array("kelompok_penyakit_id" => 3, "nama" => "Ulkus Mulut", "icd10" => "K12"),
            array("kelompok_penyakit_id" => 4, "nama" => "Astigmatisme", "icd10" => "H52.2"),
            array("kelompok_penyakit_id" => 4, "nama" => "Benda Asing di Konjungtiva", "icd10" => "T15.9"),
            array("kelompok_penyakit_id" => 4, "nama" => "Blefaritis", "icd10" => "H01.0"),
            array("kelompok_penyakit_id" => 4, "nama" => "Buta Senja", "icd10" => "H53.6"),
            array("kelompok_penyakit_id" => 4, "nama" => "Episkleritis", "icd10" => "H15.1"),
            array("kelompok_penyakit_id" => 4, "nama" => "Glaukoma Akut", "icd10" => "H40.2"),
            array("kelompok_penyakit_id" => 4, "nama" => "Glaukoma Kronis", "icd10" => "H40.2"),
            array("kelompok_penyakit_id" => 4, "nama" => "Hifema", "icd10" => "H21.0"),
            array("kelompok_penyakit_id" => 4, "nama" => "Hipermetropia", "icd10" => "H52.0"),
            array("kelompok_penyakit_id" => 4, "nama" => "Hordeolum", "icd10" => "H00.0"),
            array("kelompok_penyakit_id" => 4, "nama" => "Katarak Kongenital", "icd10" => "Q12.0"),
            array("kelompok_penyakit_id" => 4, "nama" => "Katarak pada Pasien Dewasa", "icd10" => "H26.9"),
            array("kelompok_penyakit_id" => 4, "nama" => "Konjungtivitis Alergi", "icd10" => "H10.1"),
            array("kelompok_penyakit_id" => 4, "nama" => "Konjungtivitis Infeksi", "icd10" => "H10.9"),
            array("kelompok_penyakit_id" => 4, "nama" => "Laserasi Kelopak Mata", "icd10" => "S01.1"),
            array("kelompok_penyakit_id" => 4, "nama" => "Low Vision", "icd10" => "H.54"),
            array("kelompok_penyakit_id" => 4, "nama" => "Mata Kering", "icd10" => "H04.1"),
            array("kelompok_penyakit_id" => 4, "nama" => "Miopia Ringan", "icd10" => "H52.1"),
            array("kelompok_penyakit_id" => 4, "nama" => "Pendarahan Subkonjungtiva", "icd10" => "H57.8"),
            array("kelompok_penyakit_id" => 4, "nama" => "Presbiopia", "icd10" => "H52.4"),
            array("kelompok_penyakit_id" => 4, "nama" => "Pterygium", "icd10" => "H11.0"),
            array("kelompok_penyakit_id" => 4, "nama" => "Retinoblastoma", "icd10" => "C69.21"),
            array("kelompok_penyakit_id" => 4, "nama" => "Retinopati Diabetik", "icd10" => "H36.0"),
            array("kelompok_penyakit_id" => 4, "nama" => "Trauma Kimia Mata", "icd10" => "T26"),
            array("kelompok_penyakit_id" => 4, "nama" => "Trikiasis", "icd10" => "H02"),
            array("kelompok_penyakit_id" => 5, "nama" => "Benda Asing Ditelinga", "icd10" => "T16"),
            array("kelompok_penyakit_id" => 5, "nama" => "Mastoiditis", "icd10" => "H70"),
            array("kelompok_penyakit_id" => 5, "nama" => "Otitis Eksterna", "icd10" => "H60.9"),
            array("kelompok_penyakit_id" => 5, "nama" => "Otitis Media Akut", "icd10" => "H65"),
            array("kelompok_penyakit_id" => 5, "nama" => "Otitis Media Supuratif Kronik", "icd10" => "H66"),
            array("kelompok_penyakit_id" => 5, "nama" => "Presbiakusis", "icd10" => "H91.1"),
            array("kelompok_penyakit_id" => 5, "nama" => "Serumen Prop", "icd10" => "H61.2"),
            array("kelompok_penyakit_id" => 5, "nama" => "Tuli Akibat Bising", "icd10" => "H83"),
            array("kelompok_penyakit_id" => 5, "nama" => "Tuli Kongenital", "icd10" => "H90"),
            array("kelompok_penyakit_id" => 6, "nama" => "Angina Pektoris Stabil", "icd10" => "I20.9"),
            array("kelompok_penyakit_id" => 6, "nama" => "Cardiorespiratory Arrest", "icd10" => "R09.2"),
            array("kelompok_penyakit_id" => 6, "nama" => "Gagal Jantung Akut dan Kronik", "icd10" => "I50.9"),
            array("kelompok_penyakit_id" => 6, "nama" => "Hipertensi Esensial", "icd10" => "I10"),
            array("kelompok_penyakit_id" => 6, "nama" => "Infark Miokard", "icd10" => "I21.9"),
            array("kelompok_penyakit_id" => 6, "nama" => "Takikardia", "icd10" => "I47"),
            array("kelompok_penyakit_id" => 7, "nama" => "Artritis Reumatoid", "icd10" => "M53.3"),
            array("kelompok_penyakit_id" => 7, "nama" => "Artritis, Osteoartritis", "icd10" => "M19.9"),
            array("kelompok_penyakit_id" => 7, "nama" => "Frakur Terbuka", "icd10" => "S52.9"),
            array("kelompok_penyakit_id" => 7, "nama" => "Frakur Tertutup", "icd10" => "S52.9"),
            array("kelompok_penyakit_id" => 7, "nama" => "Lipoma", "icd10" => "D17.9"),
            array("kelompok_penyakit_id" => 7, "nama" => "Osteoporosis", "icd10" => "C41"),
            array("kelompok_penyakit_id" => 7, "nama" => "Polimialgia Reumatik", "icd10" => "M53.3"),
            array("kelompok_penyakit_id" => 7, "nama" => "Reduction Deformity", "icd10" => "Q73.8"),
            array("kelompok_penyakit_id" => 7, "nama" => "Talipes", "icd10" => "Q66"),
            array("kelompok_penyakit_id" => 7, "nama" => "Vulnus", "icd10" => "T14.1"),
            array("kelompok_penyakit_id" => 8, "nama" => "Anencephaly", "icd10" => "Q00.0"),
            array("kelompok_penyakit_id" => 8, "nama" => "Bells’ Palsy", "icd10" => "G51.0"),
            array("kelompok_penyakit_id" => 8, "nama" => "Delirium", "icd10" => "F05.9"),
            array("kelompok_penyakit_id" => 8, "nama" => "Epilepsi", "icd10" => "G40.9"),
            array("kelompok_penyakit_id" => 8, "nama" => "Kejang Demam", "icd10" => "R56.0"),
            array("kelompok_penyakit_id" => 8, "nama" => "Meningo/Encephalocele", "icd10" => "Q01.9"),
            array("kelompok_penyakit_id" => 8, "nama" => "Migren", "icd10" => "G43.9"),
            array("kelompok_penyakit_id" => 8, "nama" => "Neuroblastoma", "icd10" => "C74.9"),
            array("kelompok_penyakit_id" => 8, "nama" => "Rabies", "icd10" => "A82.9"),
            array("kelompok_penyakit_id" => 8, "nama" => "Status Epileptikus", "icd10" => "G41.9"),
            array("kelompok_penyakit_id" => 8, "nama" => "Stroke", "icd10" => "I63.9"),
            array("kelompok_penyakit_id" => 8, "nama" => "Tension Headache", "icd10" => "G44.2"),
            array("kelompok_penyakit_id" => 8, "nama" => "Transient Ischemic Attack (TIA)", "icd10" => "G45.9"),
            array("kelompok_penyakit_id" => 8, "nama" => "Vertigo", "icd10" => "R42"),
            array("kelompok_penyakit_id" => 9, "nama" => "Demensia", "icd10" => "F03"),
            array("kelompok_penyakit_id" => 9, "nama" => "Gangguan Anxietas", "icd10" => "F40#"),
            array("kelompok_penyakit_id" => 9, "nama" => "Gangguan Campuran Anxietas dan Depresi", "icd10" => "F41.2"),
            array("kelompok_penyakit_id" => 9, "nama" => "Gangguan Depresi", "icd10" => "F33"),
            array("kelompok_penyakit_id" => 9, "nama" => "Gangguan Penggunaan Napza", "icd10" => "F10#"),
            array("kelompok_penyakit_id" => 9, "nama" => "Gangguan Perkembangan dan Perilaku pada Anak dan Remaja", "icd10" => "F89-90#"),
            array("kelompok_penyakit_id" => 9, "nama" => "Gangguan Psikotik", "icd10" => "F20#"),
            array("kelompok_penyakit_id" => 9, "nama" => "Gangguan Somatoform", "icd10" => "F45"),
            array("kelompok_penyakit_id" => 9, "nama" => "Insomnia", "icd10" => "F51.0"),
            array("kelompok_penyakit_id" => 10, "nama" => "Asma Bronkial", "icd10" => "J45"),
            array("kelompok_penyakit_id" => 10, "nama" => "Asfiksia", "icd10" => "R.09.0"),
            array("kelompok_penyakit_id" => 10, "nama" => "Bronkitis Akut (Usia < 15 Tahun)", "icd10" => "J20.9"),
            array("kelompok_penyakit_id" => 10, "nama" => "Bronkitis Akut (Usia > 15 Tahun)", "icd10" => "J40"),
            array("kelompok_penyakit_id" => 10, "nama" => "Difteria", "icd10" => "A36.9"),
            array("kelompok_penyakit_id" => 10, "nama" => "Epistaksis", "icd10" => "R04.0"),
            array("kelompok_penyakit_id" => 10, "nama" => "Faringitis Akut", "icd10" => "J02.9"),
            array("kelompok_penyakit_id" => 10, "nama" => "Furunkel pada Hidung", "icd10" => "J34.0"),
            array("kelompok_penyakit_id" => 10, "nama" => "Influenza", "icd10" => "J11"),
            array("kelompok_penyakit_id" => 10, "nama" => "Kanker Nasofaring", "icd10" => "C11.9"),
            array("kelompok_penyakit_id" => 10, "nama" => "Kanker Paru", "icd10" => "C34.9"),
            array("kelompok_penyakit_id" => 10, "nama" => "Laringitis Akut", "icd10" => "J04.0"),
            array("kelompok_penyakit_id" => 10, "nama" => "Penyakit Paru Obstruktif Kronis", "icd10" => "J44.9"),
            array("kelompok_penyakit_id" => 10, "nama" => "Pertunis (Batuk Rejan)", "icd10" => "A37.9"),
            array("kelompok_penyakit_id" => 10, "nama" => "Pneumonia Aspirasi", "icd10" => "J69.0"),
            array("kelompok_penyakit_id" => 10, "nama" => "Bronkopneumonia", "icd10" => "J18.0"),
            array("kelompok_penyakit_id" => 10, "nama" => "Pneumonia", "icd10" => "J18.9"),
            array("kelompok_penyakit_id" => 10, "nama" => "Pneumotoraks", "icd10" => "J93.9"),
            array("kelompok_penyakit_id" => 10, "nama" => "Rinitis Akut", "icd10" => "J00"),
            array("kelompok_penyakit_id" => 10, "nama" => "Rinitis Alergi", "icd10" => "J30.4"),
            array("kelompok_penyakit_id" => 10, "nama" => "Sinusitis Akut", "icd10" => "J01"),
            array("kelompok_penyakit_id" => 10, "nama" => "Status Asmatikus", "icd10" => "J46"),
            array("kelompok_penyakit_id" => 10, "nama" => "Tonsolitis Akut", "icd10" => "J03.9"),
            array("kelompok_penyakit_id" => 10, "nama" => "Tonsilitis Kronis", "icd10" => "J35.9"),
            array("kelompok_penyakit_id" => 11, "nama" => "Akne Vulgaris Rignan", "icd10" => "L70.0"),
            array("kelompok_penyakit_id" => 11, "nama" => "Cutaneus Larva Migrans", "icd10" => "B76.9"),
            array("kelompok_penyakit_id" => 11, "nama" => "Dermatitis Atopik", "icd10" => "L20"),
            array("kelompok_penyakit_id" => 11, "nama" => "Dermatitis Kontak Alergi", "icd10" => "L23"),
            array("kelompok_penyakit_id" => 11, "nama" => "Dermatitis Kontak Iritan", "icd10" => "L24"),
            array("kelompok_penyakit_id" => 11, "nama" => "Dermatitis Numularis", "icd10" => "L20.8"),
            array("kelompok_penyakit_id" => 11, "nama" => "Dermatitis Perioral", "icd10" => "L71.0"),
            array("kelompok_penyakit_id" => 11, "nama" => "Dermatitis Popok", "icd10" => "L22"),
            array("kelompok_penyakit_id" => 11, "nama" => "Dermatitis Seboroik", "icd10" => "L21"),
            array("kelompok_penyakit_id" => 11, "nama" => "Dermatofitosis", "icd10" => "B35"),
            array("kelompok_penyakit_id" => 11, "nama" => "Tinea Capitis dan Tinea Barbea", "icd10" => "B35.0"),
            array("kelompok_penyakit_id" => 11, "nama" => "Tinea Corporis", "icd10" => "B35.4"),
            array("kelompok_penyakit_id" => 11, "nama" => "Tinea Cruris", "icd10" => "B35.6"),
            array("kelompok_penyakit_id" => 11, "nama" => "Tinea Manuum", "icd10" => "B35.2"),
            array("kelompok_penyakit_id" => 11, "nama" => "Tinea Pedis", "icd10" => "B35.3"),
            array("kelompok_penyakit_id" => 11, "nama" => "Erisipelas", "icd10" => "A46"),
            array("kelompok_penyakit_id" => 11, "nama" => "Eritrasma", "icd10" => "L08.1"),
            array("kelompok_penyakit_id" => 11, "nama" => "Exanthematous drug Eruption", "icd10" => "L27.0"),
            array("kelompok_penyakit_id" => 11, "nama" => "Fixed Drug Eruption", "icd10" => "L27.0"),
            array("kelompok_penyakit_id" => 11, "nama" => "Frambusia RDT (+) Konfirmasi/Probable", "icd10" => "A66"),
            array("kelompok_penyakit_id" => 11, "nama" => "Herpes Simplek", "icd10" => "B00.9"),
            array("kelompok_penyakit_id" => 11, "nama" => "Herpes Zoster", "icd10" => "B02.9"),
            array("kelompok_penyakit_id" => 11, "nama" => "Hidradenitis Supuratif", "icd10" => "L73.2"),
            array("kelompok_penyakit_id" => 11, "nama" => "Liken Simpleks Kronik (Neurodermatitis Sirkumkripta)", "icd10" => "L28.0"),
            array("kelompok_penyakit_id" => 11, "nama" => "Luka Bakar Derajat I dan II", "icd10" => "T30"),
            array("kelompok_penyakit_id" => 11, "nama" => "Miliaria", "icd10" => "L74.3"),
            array("kelompok_penyakit_id" => 11, "nama" => "Moluskum Kontagiosum", "icd10" => "B08.1"),
            array("kelompok_penyakit_id" => 11, "nama" => "Pedikulosis Pubis", "icd10" => "B85.3"),
            array("kelompok_penyakit_id" => 11, "nama" => "Abses, Furuncke dan Carbucle", "icd10" => " L02"),
            array("kelompok_penyakit_id" => 11, "nama" => "Impetigo", "icd10" => "L01"),
            array("kelompok_penyakit_id" => 11, "nama" => "Pioderma", "icd10" => "L08.0"),
            array("kelompok_penyakit_id" => 11, "nama" => "Pitiriasis Rosea", "icd10" => "L42"),
            array("kelompok_penyakit_id" => 11, "nama" => "Pitiriasis Versikolor", "icd10" => "B36.0"),
            array("kelompok_penyakit_id" => 11, "nama" => "Reaksi Gigitan Serangga", "icd10" => "T63.4"),
            array("kelompok_penyakit_id" => 11, "nama" => "Sindrom Stevens Johnson", "icd10" => "L51.1"),
            array("kelompok_penyakit_id" => 11, "nama" => "Skabies", "icd10" => "B86"),
            array("kelompok_penyakit_id" => 11, "nama" => "Skrofuloderma", "icd10" => "A18.4"),
            array("kelompok_penyakit_id" => 11, "nama" => "Ulkus pada Tungkai", "icd10" => "L98"),
            array("kelompok_penyakit_id" => 11, "nama" => "Urtikaria", "icd10" => "L50"),
            array("kelompok_penyakit_id" => 11, "nama" => "Veruka Vulgaris", "icd10" => "B07"),
            array("kelompok_penyakit_id" => 12, "nama" => "Diabetes Mellitus Tipe 1", "icd10" => "E10"),
            array("kelompok_penyakit_id" => 12, "nama" => "Diabetes Mellitus Tipe 2", "icd10" => "E11"),
            array("kelompok_penyakit_id" => 12, "nama" => "Hiperglikemia Hiperosmolar Non Ketotik", "icd10" => "R73.9"),
            array("kelompok_penyakit_id" => 12, "nama" => "Hiperurisemia – Gout Arthritis", "icd10" => "E79.0"),
            array("kelompok_penyakit_id" => 12, "nama" => "Hipoglikemia", "icd10" => "E16.2"),
            array("kelompok_penyakit_id" => 12, "nama" => "Hipotiroid Kongenital", "icd10" => "E03.1"),
            array("kelompok_penyakit_id" => 12, "nama" => "Lipidemia", "icd10" => "E78.5"),
            array("kelompok_penyakit_id" => 12, "nama" => "Malnutrisi Energi Protein", "icd10" => "E46"),
            array("kelompok_penyakit_id" => 12, "nama" => "Obesitas", "icd10" => "E66.9"),
            array("kelompok_penyakit_id" => 12, "nama" => "Tirotoksikosis", "icd10" => "E05.9"),
            array("kelompok_penyakit_id" => 13, "nama" => "Epispadia", "icd10" => "Q64.0"),
            array("kelompok_penyakit_id" => 13, "nama" => "Fimosis", "icd10" => "N47"),
            array("kelompok_penyakit_id" => 13, "nama" => "Hipertropi Prostat", "icd10" => "N40"),
            array("kelompok_penyakit_id" => 13, "nama" => "Hypospadia", "icd10" => "Q54"),
            array("kelompok_penyakit_id" => 13, "nama" => "Infeksi Saluran Kemih", "icd10" => "N39.0"),
            array("kelompok_penyakit_id" => 13, "nama" => "Parafimosis", "icd10" => "N47.2"),
            array("kelompok_penyakit_id" => 13, "nama" => "Penyakit Ginjal Kronik", "icd10" => "N03"),
            array("kelompok_penyakit_id" => 13, "nama" => "Pielonefritis tanpa Komplikasi", "icd10" => "N10"),
            array("kelompok_penyakit_id" => 14, "nama" => "Abortus Inkomplit", "icd10" => "O06.4"),
            array("kelompok_penyakit_id" => 14, "nama" => "Abortus Komplit", "icd10" => "O03.9"),
            array("kelompok_penyakit_id" => 14, "nama" => "Anemia Defisiensi Besi pada Kehamilan", "icd10" => "O99.0"),
            array("kelompok_penyakit_id" => 14, "nama" => "Cracked Nipple", "icd10" => "O9212"),
            array("kelompok_penyakit_id" => 14, "nama" => "Eklampsi", "icd10" => "O15.9"),
            array("kelompok_penyakit_id" => 14, "nama" => "Hiperemesis Gravidarum", "icd10" => "O21.0"),
            array("kelompok_penyakit_id" => 14, "nama" => "Inverted Nipple", "icd10" => "O92.02"),
            array("kelompok_penyakit_id" => 14, "nama" => "Kanker Serviks", "icd10" => "C53.9"),
            array("kelompok_penyakit_id" => 14, "nama" => "Kehamilan Normal", "icd10" => "O80.9"),
            array("kelompok_penyakit_id" => 14, "nama" => "Ketuban Pecah Dini", "icd10" => "O42.9"),
            array("kelompok_penyakit_id" => 14, "nama" => "Mastitis", "icd10" => "N61"),
            array("kelompok_penyakit_id" => 14, "nama" => "Pendarahan Post Partum", "icd10" => "O72.1"),
            array("kelompok_penyakit_id" => 14, "nama" => "Persalinan Lama", "icd10" => "O63.9"),
            array("kelompok_penyakit_id" => 14, "nama" => "Pre Eklampsia", "icd10" => "O14.9"),
            array("kelompok_penyakit_id" => 14, "nama" => "Ruptur Perineum Tingkat 1-2", "icd10" => "O70.0"),
            array("kelompok_penyakit_id" => 14, "nama" => "Tumor Payudara", "icd10" => "C50.9"),
            array("kelompok_penyakit_id" => 15, "nama" => "Fluor Albus", "icd10" => "N98.9"),
            array("kelompok_penyakit_id" => 15, "nama" => "Sifilis", "icd10" => "A53.9"),
            array("kelompok_penyakit_id" => 15, "nama" => "Gonore", "icd10" => "A54.9"),
            array("kelompok_penyakit_id" => 15, "nama" => "Vaginitis", "icd10" => "N76.0"),
            array("kelompok_penyakit_id" => 15, "nama" => "Vulvitis", "icd10" => "N76.2"),
        ];

        foreach ($lists as $list) {
            DB::table('jenis_penyakits')->updateOrInsert([
                'kelompok_penyakit_id' => $list["kelompok_penyakit_id"],
                'nama' => $list["nama"],
                'icd10' => $list["icd10"]
            ]);
        }
    }
}
