<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('sumber_daya_puskesmas', function (Blueprint $table) {
            $table->id();
            $table->foreignId('identitas_puskesmas_id');
            $table->boolean('rencana_lima_tahunan')->nullable();
            $table->boolean('rencana_usulan_kegiatan')->nullable();
            $table->boolean('rencana_pelaksanaan_kegiatan_tahunan')->nullable();
            $table->boolean('rencana_pelaksanaan_kegiatan_bulanan')->nullable();
            $table->boolean('lokakarya_mini_bulanan')->nullable();
            $table->boolean('lokakarya_mini_triwulan')->nullable();
            $table->boolean('dokumen_pkp')->nullable();
            $table->integer('hasil_pelayanan_kesehatan')->nullable();
            $table->integer('hasil_manajemen')->nullable();
            $table->boolean('feedback_dinkes_yang_diterima')->nullable();
            $table->boolean('dokumen_pkp_dinkes_kota')->nullable();
            $table->integer('hasil_pelayanan_kesehatan_dinkes_kota')->nullable();
            $table->integer('hasil_manajemen_dinkes_kota')->nullable();
            $table->boolean('pelayanan_promosi_kesehatan')->nullable();
            $table->boolean('pelayanan_kesehatan_lingkungan')->nullable();
            $table->boolean('pelayanan_kia')->nullable();
            $table->boolean('pelayanan_gizi')->nullable();
            $table->boolean('pelayanan_pencegahan_pengendalian_penyakit')->nullable();
            $table->boolean('pelayanan_kesehatan_gigi_masyarakat')->nullable();
            $table->boolean('pelayanan_kesehatan_tradisional')->nullable();
            $table->boolean('pelayanan_kesehatan_olahraga')->nullable();
            $table->boolean('pelayanan_kesehatan_indera')->nullable();
            $table->boolean('pelayanan_kesehatan_kerja')->nullable();
            $table->boolean('pelayanan_kesehatan_haji')->nullable();
            $table->boolean('pelayanan_kesehatan_lainnya')->nullable();
            $table->boolean('pelayanan_pemeriksaan_umum')->nullable();
            $table->boolean('pelayanan_kesehatan_gigi_mulut')->nullable();
            $table->boolean('pelayanan_gawat_darurat')->nullable();
            $table->boolean('pelayanan_rawat_inap')->nullable();
            $table->boolean('pelayanan_satu_hari')->nullable();
            $table->boolean('perawatan_dirumah')->nullable();
            $table->boolean('pelayanan_kefamasian')->nullable();
            $table->boolean('pelayanan_keperawatan_kesehatan_masyarakat')->nullable();
            $table->boolean('pelayanan_laboratorium')->nullable();
            $table->boolean('kunjungan_keluarga')->nullable();
            $table->integer('jumlah_keluarga_yang_dilakukan_pis_pk')->nullable();
            $table->integer('jumlah_keluarga_iks_kategori_sehat')->nullable();
            $table->integer('jumlah_keluarga_iks_kategori_prasehat')->nullable();
            $table->integer('jumlah_keluarga_iks_kategori_tidaksehat')->nullable();
            $table->integer('jumlah_desa_yang_dilakukan_pis_pk')->nullable();
            $table->integer('jumlah_kelurahan_yang_dilakukan_pis_pk')->nullable();
            $table->integer('jumlah_desa_kategori_sehat')->nullable();
            $table->integer('jumlah_kelurahan_kategori_sehat')->nullable();
            $table->integer('jumlah_desa_kategori_prasehat')->nullable();
            $table->integer('jumlah_kelurahan_kategori_prasehat')->nullable();
            $table->integer('jumlah_desa_kategori_tidaksehat')->nullable();
            $table->integer('jumlah_kelurahan_kategori_tidaksehat')->nullable();
            $table->boolean('status_puskesma_blud')->nullable();
            $table->boolean('puskesmas_kerjasama_bpjs')->nullable();
            $table->integer('besar_kapitasi_untuk_puskesmas')->nullable();
            $table->integer('jumlah_peserta_jkn_terdaftar')->nullable();
            $table->integer('jumlah_dana_kapitasi_selama_1_tahun')->nullable();
            $table->integer('persentase_pengalokasian_dana_kapitasi')->nullable();
            $table->json('komponen_kegiatan_yang_dibiayai_dana_kapitasi')->nullable();
            $table->integer('klinik_pratama')->nullable();
            $table->integer('tempat_praktik_mandiri_dokter')->nullable();
            $table->integer('tempat_praktik_mandiri_dokter_gigi')->nullable();
            $table->integer('peserta_jkn')->nullable();
            $table->integer('penerima_bantuan_iuran')->nullable();
            $table->integer('non_penerima_bantuan_iuran')->nullable();
            $table->integer('peserta_asuransi_komersil')->nullable();
            $table->integer('tahun_dibangun')->nullable();
            $table->integer('luas_tanah_puskesmas')->nullable();
            $table->enum('sertifikat_tanah', ['shm', 'shgu_shgb', 'girik_dan_petik', 'acte_van_eigendom'])->nullable();
            $table->enum('kepemilikan_tanah', ['pemerintah', 'adat', 'warga', 'sewa'])->nullable();
            $table->integer('luas_lantai_dasar_bangunan')->nullable();
            $table->integer('luas_total_lantai_bangunan')->nullable();
            $table->integer('jumlah_tempat_tidur_perawatan_umum')->nullable();
            $table->integer('jumlah_tempat_tidur_perawatan_bersalin')->nullable()->nullable();
            $table->json('lokasi_gedung_puskesmas')->nullable();
            $table->date('tanggal_izin_puskesmas')->nullable();
            $table->string('no_sk_izin_puskesmas')->nullable();
            $table->string('penerbit_izin_puskesmas')->nullable();
            $table->integer('masa_berlaku_izin_puskesmas')->nullable();
            $table->date('tanggal_regis_puskesmas')->nullable();
            $table->string('no_surat_registrasi_puskesmas')->nullable();
            $table->date('tanggal_akreditasi_puskesmas')->nullable();
            $table->string('no_sk_akreditasi_puskesmas')->nullable();
            $table->string('penerbit_akreditasi_puskesmas')->nullable();
            $table->integer('masa_berlaku_akreditasi_puskesmas')->nullable();
            $table->integer('jarak_pemukiman_terjauh_ke_puskesmas')->nullable();
            $table->integer('waktu_tempuh_ke_puskesmas')->nullable();
            $table->enum('akses_jalan_depan_puskesmas', ['aspal_beton', 'tanah', 'air', 'lainnya'])->nullable();
            $table->enum('status_jalan_terdekat_puskesmas', ['jalan_pusat', 'jalan_provinsi', 'jalan_kab_kota', 'status_lainnya'])->nullable();
            $table->json('kendaraan_yang_bisa_melalui_jalan_depan_puskesmas')->nullable();
            $table->integer('jumlah_bangunan_yang_direhabilitasi_terakhir')->nullable();
            $table->integer('tahun_rehabilitasi_terakhir')->nullable();
            $table->enum('sumber_dana_rehabilitasi', ['apbn', 'apbd_provinsi', 'apbd_kab_kota', 'hibah', 'dll'])->nullable();
            $table->enum('keadaan_bangunan_puskesmas', ['baik', 'rusak_ringan', 'rusak_sedang', 'rusak_berat'])->nullable();
            $table->integer('jumlah_bangunan_pp_kondisi_baik')->nullable();
            $table->integer('jumlah_bangunan_pp_kondisi_rusak_ringan')->nullable();
            $table->integer('jumlah_bangunan_pp_kondisi_rusak_sedang')->nullable();
            $table->integer('jumlah_bangunan_pp_kondisi_rusak_berat')->nullable();
            $table->integer('jumlah_bangunan_rumah_dinas_nakes_kondisi_baik')->nullable();
            $table->integer('jumlah_bangunan_rumah_dinas_nakes_kondisi_rusak_ringan')->nullable();
            $table->integer('jumlah_bangunan_rumah_dinas_nakes_kondisi_rusak_sedang')->nullable();
            $table->integer('jumlah_bangunan_rumah_dinas_nakes_kondisi_rusak_berat')->nullable();
            $table->json('sumber_listrik')->nullable();
            $table->enum('waktu_ketersediaan_listrik', ['24_jam', 'kurang_24_jam'])->nullable();
            $table->integer('daya_listrik_terpasang')->nullable();
            $table->integer('jumlah_genset_berfungsi')->nullable();
            $table->integer('kapasitas_genset_berfungsi')->nullable();
            $table->enum('telepon_kabel', ['ada_dan_baik', 'ada_tapi_tidak_bisa_dipakai', 'tidak_ada'])->nullable();
            $table->enum('telepon_seluler', ['ada_dan_baik', 'ada_tapi_tidak_bisa_dipakai', 'tidak_ada'])->nullable();
            $table->enum('radio_komunikasi', ['ada_dan_baik', 'ada_tapi_tidak_bisa_dipakai', 'tidak_ada'])->nullable();
            $table->enum('alat_komunikasi_lain', ['ada_dan_baik', 'ada_tapi_tidak_bisa_dipakai', 'tidak_ada'])->nullable();
            $table->enum('jaringan_internet', ['ada_dan_baik', 'ada_tapi_tidak_bisa_dipakai', 'tidak_ada'])->nullable();
            $table->integer('jumlah_komputer_berfungsi_baik')->nullable();
            $table->integer('jumlah_kendaraan_roda_4_double_gardan_kondisi_baik')->nullable();
            $table->integer('jumlah_kendaraan_roda_4_double_gardan_kondisi_rusak_ringan')->nullable();
            $table->integer('jumlah_kendaraan_roda_4_double_gardan_kondisi_rusak_berat')->nullable();
            $table->integer('jumlah_kendaraan_roda_4_single_gardan_kondisi_baik')->nullable();
            $table->integer('jumlah_kendaraan_roda_4_single_gardan_kondisi_rusak_ringan')->nullable();
            $table->integer('jumlah_kendaraan_roda_4_single_gardan_kondisi_rusak_berat')->nullable();
            $table->integer('jumlah_kendaraan_perairan_kondisi_baik')->nullable();
            $table->integer('jumlah_kendaraan_perairan_kondisi_rusak_ringan')->nullable();
            $table->integer('jumlah_kendaraan_perairan_kondisi_rusak_berat')->nullable();
            $table->integer('jumlah_kendaraan_sepeda_motor_kondisi_baik')->nullable();
            $table->integer('jumlah_kendaraan_sepeda_motor_kondisi_rusak_ringan')->nullable();
            $table->integer('jumlah_kendaraan_sepeda_motor_kondisi_rusak_berat')->nullable();
            $table->integer('jumlah_kendaraan_sepeda_kondisi_baik')->nullable();
            $table->integer('jumlah_kendaraan_sepeda_kondisi_rusak_ringan')->nullable();
            $table->integer('jumlah_kendaraan_sepeda_kondisi_rusak_berat')->nullable();
            $table->integer('jumlah_kendaraan_ambulance_kondisi_baik')->nullable();
            $table->integer('jumlah_kendaraan_ambulance_kondisi_rusak_ringan')->nullable();
            $table->integer('jumlah_kendaraan_ambulance_kondisi_rusak_berat')->nullable();
            $table->enum('air_bersih', ['ada_memenuhi_syarat', 'ada_tidak_memenuhi_syarat', 'tidak_ada'])->nullable();
            $table->boolean('air_bersih_tersedia_24_jam')->nullable();
            $table->json('sumber_air_bersih')->nullable();
            $table->enum('jamban', ['ada_memenuhi_syarat', 'ada_tidak_memenuhi_syarat', 'tidak_ada'])->nullable();
            $table->enum('insenerator', ['ada_memenuhi_syarat', 'ada_tidak_memenuhi_syarat', 'tidak_ada'])->nullable();
            $table->enum('ipal', ['ada_memenuhi_syarat', 'ada_tidak_memenuhi_syarat', 'tidak_ada'])->nullable();
            $table->enum('septitank', ['ada_memenuhi_syarat', 'ada_tidak_memenuhi_syarat', 'tidak_ada'])->nullable();
            $table->boolean('mou_limbah_padat_b3_ke_pihak_lain')->nullable();
            $table->boolean('mou_limbah_cair_ke_pihak_berizin')->nullable();
            $table->integer('tabung_gas_o2_berfungsi')->nullable();
            $table->integer('tabung_gas_o2_tidak_berfungsi')->nullable();
            $table->integer('oksigen_konsentrator_berfungsi')->nullable();
            $table->integer('oksigen_konsentrator_tidak_berfungsi')->nullable();
            $table->integer('alat_pemadam_kebakaran_berfungsi')->nullable();
            $table->integer('alat_pemadam_kebakaran_tidak_berfungsi')->nullable();
            $table->boolean('sistem_proteksi_petir')->nullable();
            $table->integer('jumlah_ac_berfungsi')->nullable();
            $table->integer('jumlah_ac_tidak_berfungsi')->nullable();
            $table->integer('jumlah_puskesmas_pembantu')->nullable();
            $table->integer('jumlah_praktik_bidan_desa')->nullable();
            $table->integer('jumlah_puskesmas_keliling')->nullable();
            $table->integer('jumlah_klinik_pratama')->nullable();
            $table->integer('jumlah_klinik_utama')->nullable();
            $table->integer('jumlah_tempat_praktik_mandiri_dokter')->nullable();
            $table->integer('jumlah_tempat_praktik_mandiri_dokter_gigi')->nullable();
            $table->integer('jumlah_tempat_praktik_mandiri_bidan')->nullable();
            $table->integer('jumlah_tempat_praktik_mandiri_perawat')->nullable();
            $table->integer('jumlah_rs_kelas_d_pratama')->nullable();
            $table->integer('jumlah_apotek')->nullable();
            $table->integer('jumlah_optik')->nullable();
            $table->integer('jumlah_lab_klinik')->nullable();
            $table->integer('jumlah_faskes_tradisional')->nullable();
            $table->boolean('ada_program_kerjasama_penurunan_aki')->nullable();
            $table->integer('jumlah_rutan_dan_lapas')->nullable();
            $table->integer('jumlah_posyandu_pratama')->nullable();
            $table->integer('jumlah_posyandu_madya')->nullable();
            $table->integer('jumlah_posyandu_purnama')->nullable();
            $table->integer('jumlah_posyandu_mandiri')->nullable();
            $table->integer('jumlah_posyandu_remaja_pratama')->nullable();
            $table->integer('jumlah_posyandu_remaja_madya')->nullable();
            $table->integer('jumlah_posyandu_remaja_purnama')->nullable();
            $table->integer('jumlah_posyandu_remaja_mandiri')->nullable();
            $table->integer('jumlah_posyandu_lansia')->nullable();
            $table->integer('jumlah_poskesdes')->nullable();
            $table->integer('jumlah_poskestren')->nullable();
            $table->integer('jumlah_posbindu_ptm_aktif')->nullable();
            $table->integer('jumlah_desa_dengan_posbindu_ptm_aktif')->nullable();
            $table->integer('jumlah_pos_tb_desa_aktif')->nullable();
            $table->integer('jumlah_posmaldes_aktif')->nullable();
            $table->integer('jumlah_pos_ukk_pratama')->nullable();
            $table->integer('jumlah_pos_ukk_madya')->nullable();
            $table->integer('jumlah_pos_ukk_purnama')->nullable();
            $table->integer('jumlah_pos_ukk_mandiri')->nullable();
            $table->integer('jumlah_pod')->nullable();
            $table->integer('jumlah_polindes')->nullable();
            $table->integer('jumlah_desa_dengan_kegiatan_dana_sehat')->nullable();
            $table->integer('jumlah_peserta_dana_sehat')->nullable();
            $table->integer('jumlah_ukbm_lainnya')->nullable();
            $table->integer('jumlah_pokja_operasional_ukbm')->nullable();
            $table->integer('jumlah_pokjanal_posyandu')->nullable();
            $table->integer('jumlah_kelompok_peduli_kesehatan')->nullable();
            $table->integer('jumlah_forum_desa_siaga_aktif')->nullable();
            $table->integer('jumlah_kader_posyandu')->nullable();
            $table->integer('jumlah_kader_poskesdes')->nullable();
            $table->integer('jumlah_kader_poskestren')->nullable();
            $table->integer('jumlah_petugas_pelaksana_posbindu_ptm')->nullable();
            $table->integer('jumlah_kader_pos_tb_desa')->nullable();
            $table->integer('jumlah_kader_posmaldes')->nullable();
            $table->integer('jumlah_kader_pos_ukk')->nullable();
            $table->integer('jumlah_kader_desa_siaga_aktif')->nullable();
            $table->integer('jumlah_ormas')->nullable();
            $table->integer('jumlah_dunia_usaha')->nullable();
            $table->integer('jumlah_ingo')->nullable();
            $table->integer('jumlah_mitra_lainnya')->nullable();
            $table->integer('jumlah_kebijakan_publik_berwawasan_kesehatan')->nullable();
            $table->boolean('puskesmas_sebagai_pendidikan_nakes')->nullable();
            $table->boolean('pelayanan_kesehatan_bergerak')->nullable();
            $table->integer('jumlah_sd')->nullable();
            $table->integer('jumlah_sltp')->nullable();
            $table->integer('jumlah_slta')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('sumber_daya_puskesmas');
    }
};
