<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('kesakitan_gigi_dan_muluts', function (Blueprint $table) {
            $table->id();
            $table->date('bulan_tahun');
            $table->foreignId('identitas_puskesmas_id');
            $table->integer('jumlah_puskesmas_pembantu')->nullable();
            $table->integer('jumlah_laporan_puskesma_pembantu')->nullable();
            $table->integer('jumlah_poskesdes')->nullable();
            $table->integer('jumlah_laporan_poskesdes')->nullable();
            $table->integer('k0_4_tahun')->nullable();
            $table->integer('k0_6_tahun')->nullable();
            $table->integer('k0_11_tahun')->nullable();
            $table->integer('k0_12_tahun')->nullable();
            $table->integer('k0_14_tahun')->nullable();
            $table->integer('k0_18_tahun')->nullable();
            $table->integer('k0_34_tahun')->nullable();
            $table->integer('k0_44_tahun')->nullable();
            $table->integer('k0_64_tahun')->nullable();
            $table->integer('k0_lebih_64_tahun')->nullable();
            $table->integer('k0_l')->nullable();
            $table->integer('k0_p')->nullable();
            $table->integer('k1_4_tahun')->nullable();
            $table->integer('k1_6_tahun')->nullable();
            $table->integer('k1_11_tahun')->nullable();
            $table->integer('k1_12_tahun')->nullable();
            $table->integer('k1_14_tahun')->nullable();
            $table->integer('k1_18_tahun')->nullable();
            $table->integer('k1_34_tahun')->nullable();
            $table->integer('k1_44_tahun')->nullable();
            $table->integer('k1_64_tahun')->nullable();
            $table->integer('k1_lebih_64_tahun')->nullable();
            $table->integer('k1_l')->nullable();
            $table->integer('k1_p')->nullable();
            $table->integer('k2_4_tahun')->nullable();
            $table->integer('k2_6_tahun')->nullable();
            $table->integer('k2_11_tahun')->nullable();
            $table->integer('k2_12_tahun')->nullable();
            $table->integer('k2_14_tahun')->nullable();
            $table->integer('k2_18_tahun')->nullable();
            $table->integer('k2_34_tahun')->nullable();
            $table->integer('k2_44_tahun')->nullable();
            $table->integer('k2_64_tahun')->nullable();
            $table->integer('k2_lebih_64_tahun')->nullable();
            $table->integer('k2_l')->nullable();
            $table->integer('k2_p')->nullable();
            $table->integer('k3_4_tahun')->nullable();
            $table->integer('k3_6_tahun')->nullable();
            $table->integer('k3_11_tahun')->nullable();
            $table->integer('k3_12_tahun')->nullable();
            $table->integer('k3_14_tahun')->nullable();
            $table->integer('k3_18_tahun')->nullable();
            $table->integer('k3_34_tahun')->nullable();
            $table->integer('k3_44_tahun')->nullable();
            $table->integer('k3_64_tahun')->nullable();
            $table->integer('k3_lebih_64_tahun')->nullable();
            $table->integer('k3_l')->nullable();
            $table->integer('k3_p')->nullable();
            $table->integer('k4_4_tahun')->nullable();
            $table->integer('k4_6_tahun')->nullable();
            $table->integer('k4_11_tahun')->nullable();
            $table->integer('k4_12_tahun')->nullable();
            $table->integer('k4_14_tahun')->nullable();
            $table->integer('k4_18_tahun')->nullable();
            $table->integer('k4_34_tahun')->nullable();
            $table->integer('k4_44_tahun')->nullable();
            $table->integer('k4_64_tahun')->nullable();
            $table->integer('k4_lebih_64_tahun')->nullable();
            $table->integer('k4_l')->nullable();
            $table->integer('k4_p')->nullable();
            $table->integer('k5_4_tahun')->nullable();
            $table->integer('k5_6_tahun')->nullable();
            $table->integer('k5_11_tahun')->nullable();
            $table->integer('k5_12_tahun')->nullable();
            $table->integer('k5_14_tahun')->nullable();
            $table->integer('k5_18_tahun')->nullable();
            $table->integer('k5_34_tahun')->nullable();
            $table->integer('k5_44_tahun')->nullable();
            $table->integer('k5_64_tahun')->nullable();
            $table->integer('k5_lebih_64_tahun')->nullable();
            $table->integer('k5_l')->nullable();
            $table->integer('k5_p')->nullable();
            $table->integer('k7_4_tahun')->nullable();
            $table->integer('k7_6_tahun')->nullable();
            $table->integer('k7_11_tahun')->nullable();
            $table->integer('k7_12_tahun')->nullable();
            $table->integer('k7_14_tahun')->nullable();
            $table->integer('k7_18_tahun')->nullable();
            $table->integer('k7_34_tahun')->nullable();
            $table->integer('k7_44_tahun')->nullable();
            $table->integer('k7_64_tahun')->nullable();
            $table->integer('k7_lebih_64_tahun')->nullable();
            $table->integer('k7_l')->nullable();
            $table->integer('k7_p')->nullable();
            $table->integer('k8_4_tahun')->nullable();
            $table->integer('k8_6_tahun')->nullable();
            $table->integer('k8_11_tahun')->nullable();
            $table->integer('k8_12_tahun')->nullable();
            $table->integer('k8_14_tahun')->nullable();
            $table->integer('k8_18_tahun')->nullable();
            $table->integer('k8_34_tahun')->nullable();
            $table->integer('k8_44_tahun')->nullable();
            $table->integer('k8_64_tahun')->nullable();
            $table->integer('k8_lebih_64_tahun')->nullable();
            $table->integer('k8_l')->nullable();
            $table->integer('k8_p')->nullable();
            $table->integer('k12_4_tahun')->nullable();
            $table->integer('k12_6_tahun')->nullable();
            $table->integer('k12_11_tahun')->nullable();
            $table->integer('k12_12_tahun')->nullable();
            $table->integer('k12_14_tahun')->nullable();
            $table->integer('k12_18_tahun')->nullable();
            $table->integer('k12_34_tahun')->nullable();
            $table->integer('k12_44_tahun')->nullable();
            $table->integer('k12_64_tahun')->nullable();
            $table->integer('k12_lebih_64_tahun')->nullable();
            $table->integer('k12_l')->nullable();
            $table->integer('k12_p')->nullable();
            $table->integer('k13_4_tahun')->nullable();
            $table->integer('k13_6_tahun')->nullable();
            $table->integer('k13_11_tahun')->nullable();
            $table->integer('k13_12_tahun')->nullable();
            $table->integer('k13_14_tahun')->nullable();
            $table->integer('k13_18_tahun')->nullable();
            $table->integer('k13_34_tahun')->nullable();
            $table->integer('k13_44_tahun')->nullable();
            $table->integer('k13_64_tahun')->nullable();
            $table->integer('k13_lebih_64_tahun')->nullable();
            $table->integer('k13_l')->nullable();
            $table->integer('k13_p')->nullable();
            $table->integer('k51_4_tahun')->nullable();
            $table->integer('k51_6_tahun')->nullable();
            $table->integer('k51_11_tahun')->nullable();
            $table->integer('k51_12_tahun')->nullable();
            $table->integer('k51_14_tahun')->nullable();
            $table->integer('k51_18_tahun')->nullable();
            $table->integer('k51_34_tahun')->nullable();
            $table->integer('k51_44_tahun')->nullable();
            $table->integer('k51_64_tahun')->nullable();
            $table->integer('k51_lebih_64_tahun')->nullable();
            $table->integer('k51_l')->nullable();
            $table->integer('k51_p')->nullable();
            $table->integer('r51_4_tahun')->nullable();
            $table->integer('r51_6_tahun')->nullable();
            $table->integer('r51_11_tahun')->nullable();
            $table->integer('r51_12_tahun')->nullable();
            $table->integer('r51_14_tahun')->nullable();
            $table->integer('r51_18_tahun')->nullable();
            $table->integer('r51_34_tahun')->nullable();
            $table->integer('r51_44_tahun')->nullable();
            $table->integer('r51_64_tahun')->nullable();
            $table->integer('r51_lebih_64_tahun')->nullable();
            $table->integer('r51_l')->nullable();
            $table->integer('r51_p')->nullable();
            $table->integer('s2_4_tahun')->nullable();
            $table->integer('s2_6_tahun')->nullable();
            $table->integer('s2_11_tahun')->nullable();
            $table->integer('s2_12_tahun')->nullable();
            $table->integer('s2_14_tahun')->nullable();
            $table->integer('s2_18_tahun')->nullable();
            $table->integer('s2_34_tahun')->nullable();
            $table->integer('s2_44_tahun')->nullable();
            $table->integer('s2_64_tahun')->nullable();
            $table->integer('s2_lebih_64_tahun')->nullable();
            $table->integer('s2_l')->nullable();
            $table->integer('s2_p')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('kesakitan_gigi_dan_muluts');
    }
};
